# Variables


In [ ]:
# 1. First Position of Variables is Underscore or alphabets
mycity = 30
print(mycity)
_mycity = "Chaksu"
print(_mycity)

In [ ]:
# 2. Pull - remaining part of variable is letter , underscore , number
my_city1 = "Jaipur"
print(my_city1)

my1 = "chaksu"
print(my1)

In [ ]:
# 3. Case Sensitive 
my_city = "Jaipur"
print(my_city)



In [ ]:
# 4. Variable is not contain space , any symbol
my city = "Jaipur"
print(my city)

In [ ]:
# 5. Good practice to make variable small letter with underscore 

In [ ]:
# 6. To  make varibale name a void keyword of the python 
for , in , True , False , List

keyword means - already reserved in python 

In [ ]:
import keyword
print(keyword.kwlist)   

# Data Types


In [ ]:
# 1 . Numerical 
  #a. integer 
      # 1,2,3.....
  #b. Floating point numbers 
      # 1.1  ,3.1 , 4.2 , 5.6 ,.......
  #c. Complex             in mathematics 
      # 2+3j              # 2+3i

In [ ]:
a  = 1
type(a)

int

In [ ]:
b = 3.14
type(b)

float

In [ ]:
c = 3+4j
type(c)

complex

In [ ]:
# 2. String
     # text , word or sentence 

x = "Hello world"
type(x)

str

In [ ]:
# 3. Boolean  
     # True & False

a = True
type(a)
b = False
type(b)

bool

In [ ]:
# 4. None Type

a = None 
type(a)

NoneType

# Operators


In [ ]:
# 1. Arithematic Operator

  #a. Addition Operator 

x = 24 
y = 26
z = x+ y
print(z) 

50


In [ ]:
# b. Substraction 
x = 23
y = 3
z = x-y
print(z)

20


In [ ]:
# c. Multiplication
x = 4
y = 5
z = x * y 
print(z)

20


In [ ]:
# d. Division
x = 50
y = 10
z = x/y
print(z)

5.0


In [ ]:
x = 50
y = 10
z = x//y
print(z)

5


In [ ]:
# e. Expontiation(**)
     # means X power Y . 
x = 2
y = 5
z = x ** y
print(z)

32


In [ ]:
# f. Floor Division(//)
# it will be give only " Quotient" in output in the both format (integer and float)
x = 7
y = 2
z = x//y
print(z)
# one value are be float then output will be in "float" 
x = 7
y = 2.0
z = x//y
print(z)

3
3.0


In [ ]:
# 2. Assignment Operator (=)


In [ ]:
# Compound Assignment operator (arithmatic + assignment)


10


In [ ]:
# Case 1 - :-  +=

a = 5
a+=5   # a = a + 5
print(a)




a = 5
a=+5            # that is not a correct syntax 
print(a)

10
5


In [ ]:
# Case 2 :-  -=

a = 20
a-=10       # a = a-10
print(a)

10


In [ ]:
# Case 3 :- *=

a = 5 
a*=10
print(a)

50


In [ ]:
# Case 4 :- /=

a = 25 
a/=5
print(a)

b = 25 
b/=10
print(b)

5.0
2.5


In [ ]:
# Case 5 :- **=

a = 2
a **=5      # a = 2*2*2*2*2 
print(a)

32


In [ ]:
# Case 6 :- //=

a = 7 
a //= 3
print(a)

2


In [ ]:
# Comparison Operator 

  # result is in boolean - True or False



In [ ]:
# Case 1 :- == )(equal to )
a = 10 
b = 20 
print(a == b)


False


In [ ]:
# Case 2 :- != (not equal to )

a = 10 
b = 20 
print(a != b)

True

In [ ]:
# Case 3 :- > (greater than )

a = 10 
b = 20 
print(b > a) 

True


In [ ]:
# Case 4 :- < (smaller than )

a = 10 
b = 20 
print(a < b)

True

In [ ]:
# Case 5 :- >= (greater than equal to )
          # one condition will be followed 

a = 10 
b = 10 
print(a >= b) 

a = 20 
b = 10 
print(a >= b) 

True
True


In [ ]:
 #  Case 6 :- <= (smaller than equal to )

a =10
b = 20 
print(a<=b)

True


In [ ]:
# 3. Logical Operator 


In [ ]:
# a. AND operator 
     # it return true  , if both statement are true  

x = 20 
print(x>2 and x >15)

True


In [ ]:
# b. OR operator 
     # it return true , if one of the stetement are true 

x = 10 
print(x > 5 or x > 20 )


True


In [ ]:
# c. NOT operator 
     # it reverse the result 

x = 10 
print(not(x > 5 and x < 20 ))

False


In [ ]:
# 4. Identify Operator 
     # check the memory address of two value  OR  check the value of same part of memory 

In [ ]:
# a. is 

x1 = "Jaipur"
x2 = 1234
y1 = "Jaipur"
y2 = 1234
                               # check the memory address - print(id(x1))  & print(id(y1))
x1 is y1

True

In [ ]:
x1 = "Jaipur"
x2 = 1234
y1 = "Jaipur"
y2 = 1234

print(id(x1))

140310329207472


In [ ]:
x1 = "Jaipur"
x2 = 1234
y1 = "Jaipur"
y2 = 1234
print(id(y1))

140310329207472


In [ ]:
# b. is not 

x1 = "Jaipur"
x2 = 1234
y1 = "Jaipur"
y2 = 1234

x1 is not y1

False

In [ ]:
x1 = "Jaipur"
y1 = 24
x2= "Jaipur"
y2 = 24
x1 is not y1

True

In [ ]:
x1 = "Jaipur"
x2 = 1234
y1 = "Jaipur"
y2 = 1234

x1 is not x2

True

In [ ]:
# 5. Membership operator 


In [ ]:
# a. In 
  # it return "True" if the given object present in the specified collection 
 
x1 = "jaipur"

"a" in x1

"z" in x1 



False

In [ ]:
# b. Not-In 
  # it return "True" if the given object present in the specified collection 


x1 = "jaipur"

"a" not in x1

"z" not in x1 



True



```
# This is formatted as code
```

# Modulus


In [ ]:
# Modulus = % - it show in the result is  reminder 
5 % 2 


1

In [ ]:
x = 5
y = 3
z = x%y
print(z)

2


# Data Structure

It is fundamental of programming language around which program is made 

    * Mutable - To change 
      :- List , Dictionary , Set 

    * Immutable - Not change 
      :-  String , Tuple , Number 

1. String❎
2. List❎
3. Tuple❎
4. Sets❎
5. Dictionary❎







  


#  1. String❎

It is sequence of character constructed by single , double 
and triple quotes.
String is Text , word , sentence , paragraph , entire cyclopedia.

  Example :- 
             my_sub = "Machine Learning" 
             my_sub1 = 'Deep Learning'
             my_sub2 = '''Artificial Intelligence'''


  ▶ Indexing :- It is represent the location of the element
                    

            ⚛ Positive Indexing :- Start from 0 and end with "length -1"
                        Example:- 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
                                  M A C H I N E   L  E  A  R  N  I  N  G
                                 
                                  
            ⚛ Negative Indexing :- Start from -1 and end with "-length"

                      Example:- -1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16
                                 M A C H I N E   L  E  A  R  N  I  N  G


  ▶ Slicing :- Grab the data upto designated point 

           Syntax :- Variable[ SI : EI : SS ]
                             where:- SI - Strting Index
                                     EI - Ending Index
                                     SS - Step Size 

                         * Starting index is include 
                         * ending index is exclude
                         * step size represent the step and direction 
                           slicing   



                      Example :- my_sub = Machine Learning 
                                 my_sub[0:10:1] 
                              Output :- Machine Le

  ▶ Properties of String

     1. Immutability
        
           my_name = first_name + " " + last_name
           print(my_name)

     2. Conctenate 
           first_name = "Adam"
           last_name = "Gilchrist"
           my_name = first_name + last_name
           print(my_name)


  ▶ String Methods

    1. Lower() :- this method used to convert the string into lowercase
                   Example:- my_sub = "Machine Learning"
                             print(my_sub.lower())

    2. Upper() :- this method used to convert the string into uppercase
                  Example:- my_sub = "Machine Learning"
                            print(my_sub.upper())

                
    3. Count() :- this method used to count the character of particular 
                  string
                   
                  Count(Value , SI , EI)

                  Example :- my_sub  = "Machine Learning"
                             print(my_sub.count("a" , 0 , 6))

    4. Find() :- this method return the index of first 
                 occurance of character in particular string

                 Find(Value , SI , EI)

                 Example:-  my_sub  = "Machine Learning" 
                            print(my_sub.find("n"))



    5. Replace() :-  this method replaces the old word with new word in 
                     the entire string.

                     Example:- my_sub = "Machine Learning"
                               print(my_sub.replace(" " , "_"))



          


  ▶ Format String

    first_name = "Sumit " 
    last_name = "Aandhe"
    name = f"Good Morning {first_name}{last_name}"
    print(name)



In [ ]:
my_sub = "Machine Learning" 
my_sub1 = 'Deep Learning'
my_sub2 = '''Artificial Intelligence'''

In [ ]:
my_city = "Jaipur"
type(my_city)

str

In [ ]:
my_sub = "Machine Learning"
len(my_sub)

16

In [ ]:
my_sub = "Machine Learning"
print(my_sub[0:10:1])


my_sub = "Machine Learning"
print(my_sub[0:10:2])


my_sub = "Machine Learning"
print(my_sub[0:15:3])

my_sub = "Machine Learning"
print(my_sub[0:16:4])

my_sub = "Machine Learning"
print(my_sub[5:15:5])


my_sub = "Machine Learning"
print(my_sub[0:10:-1])

Machine Le
McieL
Mheen
MiLn
na



In [ ]:
my_sub = "Machine Learning"
print(my_sub[14:-14:-1])




#-16-15-14-13-12-11-10-9-8-7 -6 -5 -4 -3 -2 -1
# M  a  c  h  i  n  e    L e  a  r  n  i  n  g
# 0  1  2  3  4  5  6  7 8 9 10 11 12 13 14 15 



ninraeL enih


In [ ]:
first_name = "Adam "
last_name = "Gilchrist"
my_name = first_name + last_name
print(my_name)

Adam Gilchrist


In [ ]:
# Lower()

my_sub = "Machine Learning"
print(my_sub.lower())

machine learning


In [ ]:
# Upper

my_sub = "Machine Learning"
print(my_sub.upper())

MACHINE LEARNING


In [ ]:
# Count 
 
my_sub  = "Machine Learning" 
print(my_sub.count("a"))

2


In [ ]:
# Count
my_sub  = "Machine Learning" 
print(my_sub.count("a" , 0 , 16))

2


In [ ]:
# Find 

my_sub  = "Machine Learning"
print(my_sub.find("n"))

# it will find "first Occurance" of the given character or any

my_sub  = "Machine Learning"
print(my_sub.find("n" , 6 , 14 ))



5
12


In [ ]:
# Replace 
my_sub = "Machine Learning"
print(my_sub.replace(" " , "_"))

Machine_Learning


In [ ]:
first_name = "Sumit " 
last_name = "Aandhe"
name = f"Good Morning {first_name}{last_name}"
print(name)

Good Morning Sumit Aandhe


# 2. List❎

▶ Sequence of item 

▶ Unlike of string 

    ⚛ it is mutable

▶ Constructed by square bracket[] and element is seprated by comma 

Example :- my_list = [1,2,3,4,5]

▶ List is Homogeneous and Heterogeneous 

    ⚛ Homogeneous :- Similar Data Type
    Example :- list = [1,2,3,4,5]  that all are integer

    ⚛ Heterogeneous :- Different data type 
    Example :- ["Apple" , 2 , 3.14 , True] that are different-2 data 
    type

▶ Indexing of list

    ⚛ Location of item 

    Negative indexing -6  -5  -4  -3        -2     -1
          Example :- [ 7 , 8 , 9,"Apple" , 3.14 , True]
    Positive indexing  1   2   3   4        5      6

▶ Slicing Of List 
    Grab the data upto designated point 
    
    my_list = [SI : EI : SS]

    my_list = [ 7 , 8 , 9,"Apple" , 3.14 . True]
    my_list[0:5:1]

▶ Properties of List  
  1. Mutable - To Change 
  2. Concatenate - To Addition


    Example:- list1 = [4,5,6]
              list2 = [7,8,9]
              my_list = list1 + list2
              print(my_list)

▶ Function Of List    
  1. len() - this function represent the length of the list 
  2. min() - this function return minimum element of the list 
             * applied only similar data type 

  3. max() - this function return maxixmum element of the list
             * applied only similar data type

  4. sum() - this function return sum of the item 
             * applied only numerical data type 

  5. sorted() - this function return the sorted list 
                * Ascending and Descending Order 
                * applied only similar data type 
                * "Reverse" boolean take as a argument 


▶ List Method 
  1. Append() - this method used to append(add) the item into end of the list
* item take as a argument

                 
                Example:- my_list = [4,7,8,9,5]
                          my_list.append(9)
                          print(my_list)

  2. Extend() - this method used to merge the list 
                
                Example :- my_list = [4 , 7, 8 ,9 ,12]
                           my_list.extend(["Apple" , "Banana"])
                           print(my_list)

  3. Pop() - this method used to pop off item from the list
* by default remove last index of the element
* "index number" as an argument in the pop() 

                Example :- my_list = [4 , 7, 8 ,9 ,12]
                           my_list. pop()
                           print(my_list)

  4. Remove() - this method used to remove the  item from the list
* "item" and "element" as an argument in the remove()
                  Example :- my_list = [4 , 7, 8 ,9 ,12]
                           my_list.remove(9)
                           print(my_list) 

  5. Count() - this method used to count the item in specified collection
                  Example :- my_list = [4 , 7, 8 ,9 ,4,5,4,78,4,2,1,4]
                           my_list.count(4)
                           print(my_list)


  6. Index() - this method used to find the index of specified item
                    Example :- my_list = [4 , 7, 8 ,9 ,12]
                           my_list.index(9)
                           print(my_list) 

  7. sort() - this method used to sorted the list
* by default sorted in ascending order 
* in descending order sorted , use "reverse = True"

                          Example :- my_list = [7,8,5,2,3,9]
                                     my_list.sort() - ascending order
                                     print(my_list)
                                     my_list.sort(reverse = True)
                                     print(my_list) - Descending order


  8. Reverse() - this method used to reverse the list 
          Example:-   my_list = [7,8,5,2,3,9]
                      my_list.reverse()
                      print(my_list)   


▶ Nested List 
* list support Nesting 
* data structure with data structure 
                 
                 Example :- list1 = [1,2,3]
                            list2 = [4,5,6]
                            list3 = [7,8,9]
                            list_of_list = [list1 , list2 , list3]
                            print(list_of_list)






In [ ]:
# Example of List 
# To we check "type" and "length" 
fruit_list = ["Apple" , "Banana" , "Mango"]
print(type(fruit_list))
print(len(fruit_list))

<class 'list'>
3


In [ ]:
# List Indexing
my_list = [7,8,9,"Apple" , 3.14 , True]
print(my_list[3])
print(my_list[-2])

Apple
3.14


In [ ]:
# Slicing of List

my_list = [7 , 8 , 9,"Apple" , 3.14 , True]
my_list[0:5:1]

[7, 8, 9, 'Apple', 3.14]

In [ ]:
# Slicing of List

# N.I. -   -6 -5  -4    -3       -2     -1 
my_list = [7 , 8 , 9,"Apple" , 3.14 , True]
# P.I. -   0   1   2    3         4      5
my_list[5:1:-1]

[True, 3.14, 'Apple', 9]

In [ ]:
# Slicing of List

my_list = [7 , 8 , 9,"Apple" , 3.14 , True]
my_list[0:5]

[7, 8, 9, 'Apple', 3.14]

In [ ]:
# Slicing of List
my_list = [7,11,13,12,14,18,19]
print(my_list[:])
print(my_list[2:])
print(my_list[:5])

[7, 11, 13, 12, 14, 18, 19]
[13, 12, 14, 18, 19]
[7, 11, 13, 12, 14]


In [ ]:
# Example of List Properties 
list1 = [4,5,6]
list2 = [7,8,9]
my_list = list1 + list2
print(my_list)

[4, 5, 6, 7, 8, 9]


In [ ]:
# Exapmle of List Function

my_list = [4,5,6,2,1,3]
list1 = [78,56,43,1,0]

# 1. len() function
print(len(my_list))

# 2. min() function
print(min(my_list))
print(min(list1))

# 3. max() function
print(max(my_list))
print(max(list1))

# 4. sum() function
print(sum(my_list))
print(sum(list1))

# 5. Sorted() function 
print(sorted(my_list))
print(sorted(list1))

     # 

print(sorted(my_list , reverse = True))
print(sorted(list1 , reverse = True ))


6
1
0
6
78
21
178
[1, 2, 3, 4, 5, 6]
[0, 1, 43, 56, 78]
[6, 5, 4, 3, 2, 1]
[78, 56, 43, 1, 0]


In [ ]:
# Methods of list

# 1. append() 
my_list = [4,7,8,9,5]
my_list.append(9) 
print(my_list)

# 2. Extend()
my_list = [4,7,8,9,12] 
my_list.extend(["apple" , "banana"]) 
print(my_list)

# 3. Pop()
my_list = [4,7,8,9,12] 
my_list.pop(1)
print(my_list)

my_list.pop() 
print(my_list)

my_list.pop(1)
print(my_list)


# 4. Remove() 
my_list = [4,7,8,9,12] 
my_list.remove(9)
print(my_list)

# 5. Count()
my_list = [1,2,3,4,1,1,1,3,2,1,1,2,3,1]
print(my_list.count(1))

# 6. Index()
my_list = [4,7,8,9,12] 
print(my_list.index(9))
 

# 7. sort()

my_list = [7,8,5,2,3,9]
my_list.sort()
print(my_list)
my_list.sort(reverse = True)  # for descending order
print(my_list)

# 8. Reverse()

my_list = [7,8,5,2,3,9]
my_list.reverse()
print(my_list)



[4, 7, 8, 9, 5, 9]
[4, 7, 8, 9, 12, 'apple', 'banana']
[4, 8, 9, 12]
[4, 8, 9]
[4, 9]
[4, 7, 8, 12]
7
3
[2, 3, 5, 7, 8, 9]
[9, 8, 7, 5, 3, 2]
[9, 3, 2, 5, 8, 7]


In [ ]:
# Nested list 

list1 = [1,2,3] 
list2 = [4,5,6]
list3 = [7,8,9]
list_of_list = [list1,list2,list3]
print(list_of_list)
list_of_list[0][1] 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


2

# 3. Tuple❎


* one type of sturucture in python 
* they are immutable means tuple cannot change
* constructed by parenthesis () and item is seprated by comma.

                    Example:- my_tuple = (1,2,3,4)
                              type(my_tuple)




▶ Methods of Tuple
  1. Index() 
  2. Count()

🔕Note:- Due to immutability tuple is not support following method 

         1. Append   2. extend  3. pop   4. remove 


▶ Multiple tuple with list 
   1. Zip() - in this function we give the multiple list as an argument and zip them together

                  Example:- city_list = ["Mohali" , "Kanpur" , "Jaipur"]
                            state_list = ["Punjab","U.P.","Rajasthan"]
                            list(zip(city_list , state_list))



In [ ]:
# Tuple 

my_tuple = (1,2,3,44)
print(type(my_tuple))

my_tuple1 = 1,2,3
print(type(my_tuple))

my_tuple2 = ()
print(type(my_tuple))

my_tuple3 = (1)
print(type(my_tuple3))

my_tuple4 = (1,)
print(type(my_tuple))


# indexing of tuple 

my_tuple = (1,2,3,4,5,67,89)
print(my_tuple[-3])
print(my_tuple[-5])
print(my_tuple[3])
print(my_tuple[5])

# Slicing of Tuple

my_tuple = (4,5,2,3,1,8)
print(my_tuple[1:5:1])


                      # Methods of tuple
# 1. Index()

my_tuple = (1,2,3,4,5,6,7)
print(my_tuple.index(2))


# 2. Count()
my_tuple = (1,2,3,1,2,3,1,5,1,5,1,3,1,6,1,7,1,8)
print(my_tuple.count(1))  

# Multiple tuple with list 

# Zip() function

city_list = ["Mohali" , "Kanpur" , "Jaipur"]
state_list = ["Punjab","U.P.","Rajasthan"]
print(list(zip(city_list , state_list)))                    # 'z' of zip , in small letter , cannot be in capital letter
                            

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'int'>
<class 'tuple'>
5
3
4
67
(5, 2, 3, 1)
1
8
[('Mohali', 'Punjab'), ('Kanpur', 'U.P.'), ('Jaipur', 'Rajasthan')]


# 4. Sets❎

* it is a data structure
* it is a uunordered collection of unique element 
* their is no duplicate item 
* it is mutable
* constructed by set()
* non-entry set represent by curly braces {} and item is seperated by comma
   
         Example:- my_set = {4,5,6,7,8}
                   empty_set = set()

                   
🔕 Note: -

           empty_set = set()

           empty_list = []

           empty_tuple = ()

           empty_dict = {}


▶ Methods of set
  1. add() - used to add item in the set 
  2. update() - used for add multiple item in a set
  3. remove() - used to remove the item 
  4. Union() - print all the element in the sets , but does not allow repeat element
  5. intersection() - print the common element in the "both" sets 
  6. difference() - remove completely in one set of other set 
  7. Symmetric difference(^) - remove intersection part



In [ ]:
# Set 

my_list = [4,5,4,6,4,5,7,8,9,6]
print(set(my_list))


# Set not contain mutable item 
'''my_set = {4,5,6,7,[8,9]}
print(my_set) 
'''
# set contain immutable item 
my_set = {4,5,6,7,(8,9)}
print(my_set) 

             # methods of sets 
# 1. add()

my_set = set()
my_set.add('a')
print(my_set)

my_set.add('b')
print(my_set)


# 2. update()

my_set = {4,5,6,7,8}
my_set.update([1,2,3,4])
print(my_set)

# 3. Remove()

my_set = {4,5,6,7,8}
my_set.remove(8)
print(my_set)



# 4. Union() 
# union represent by " | " 

a = {1,2,3,4,5}
b = {4,5,6,7,8}
print(a.union(b))
print(a|b)


# 5. Intersection() 
# represent by " & "

a = {1,2,3,4,5}
b = {4,5,6,7,8}
print(a.intersection(b))
print(a&b)

# 6. Difference()
# represent by " - "
a = {1,2,3,4,5}
b = {4,5,6,7,8}
print(a.difference(b))
print(a-b)
print(b-a)

# 7. Symmetric difference 
# represent by " ^ "

a = {1,2,3,4,5}
b = {4,5,6,7,8}
print(a.symmetric_difference(b))
print(a^b)



{4, 5, 6, 7, 8, 9}
{(8, 9), 4, 5, 6, 7}
{'a'}
{'a', 'b'}
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{4, 5}
{1, 2, 3}
{1, 2, 3}
{8, 6, 7}
{1, 2, 3, 6, 7, 8}
{1, 2, 3, 6, 7, 8}


#  Dictionary❎

* Dictionary is a collection of "key-value" pair
* constructed by curlybraces {}
      Example :- { key1 : value1 , key2 : value2}
* key and value is seprated by colon 
* item are seprated by commas

▶ Methods od Dictionary 
1. keys() - this method used to extract the keys of dictionary

                Example:- my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"}
                          list(my_dict.keys())

2. values() - this method used to extract the values of dictionary 

                Example:- my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"}
                          list(my_dict.values())

3. Items() - used to extract the keys and values 
                Example:- my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"}
                          list(my_dict.items())

4. Get() - in this method , we give key as a argument and return the value of respective key 
* if key is not found then return "None"
                Example:-my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
                         print(my_dict.get("Raj"))
                         print(my_dict.get("H.P."))


5. Update() - used to update the dictionary 
               Example:- my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
                         my_dict.update({"Guj":"Ahmda"})
                         print(my_dict)


6. Zip() - this function take multiple list as an argument.
                Example:-state_list = ["UP" , "HP" , "KAR"]
                         River_list = ["Ganga" , "Bias" , "Krishna"]
                         dict(zip(state_list , River_list))
                



In [ ]:
my_dict = {"U.P." : "Lucknow" , "Rajasthan" : "Jaipur"}
type(my_dict)
print(my_dict)

{'U.P.': 'Lucknow', 'Rajasthan': 'Jaipur'}


In [ ]:
my_dict = {"U.P." : "Lucknow" , "Rajasthan" : "Jaipur"}
print(my_dict["U.P."])
print(my_dict["Rajasthan"])

Lucknow
Jaipur


In [ ]:
                     # Methods of Dictionary 
# 1. keys()
my_dict = {"U.P." : "Lucknow" , "Rajasthan" : "Jaipur"}
list(my_dict.keys())


['U.P.', 'Rajasthan']

In [ ]:
# 2. values()
my_dict = {"U.P." : "Lucknow" , "Rajasthan" : "Jaipur"}
list(my_dict.values())

['Lucknow', 'Jaipur']

In [ ]:
# 3. Items()
my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
list(my_dict.items())

[('U.P.', 'Luck'), ('Raj', 'Jaipur')]

In [ ]:
# 4. Get()
my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
print(my_dict.get("Raj"))

print(my_dict.get("H.P."))

Jaipur
None


In [ ]:
# 5. Update()
my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
my_dict.update({"Guj":"Ahmda"})
print(my_dict)

my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
my_dict.update({"U.P.":"Mathura"})              # help of update function , update the "values" of 'keys' 
print(my_dict)


my_dict = {"U.P." : "Luck" , "Raj" : "Jaipur"} 
my_dict.update({"Jais":"Jaipur"})             # help of update function , we can not update the "keys" of 'values' 
print(my_dict)

{'U.P.': 'Luck', 'Raj': 'Jaipur', 'Guj': 'Ahmda'}
{'U.P.': 'Mathura', 'Raj': 'Jaipur'}
{'U.P.': 'Luck', 'Raj': 'Jaipur', 'Jais': 'Jaipur'}


In [ ]:
# 6. zip() 
state_list = ["UP" , "HP" , "KAR"]
River_list = ["Ganga" , "Bias" , "Krishna"]
print(dict(zip(state_list , River_list)))

{'UP': 'Ganga', 'HP': 'Bias', 'KAR': 'Krishna'}


# Statement❎

⚛ Statement is an instruction that python intrepreter is execute.

⚛ for , import , if , elif ,assignment 



▶Expression
      ___________         _______________________
     |  x = 45   |        |Variable,operator,value| <---Statement 
     |  print(x) |        |_______________________|  
     -------------
              ^
              |___Expression
               
          Expression is needed to evaluation

▶ Multi-line statement

            a,b,c,d = 4,5,6,7


▶ IF-Elif-Else Statement 

                if condition1:
                    perform action1

                elif condition2:
                    perform action2

                else:
                    perform action3


  🔕 Note:- 
   * "if" statement perform action when condition is true
   * "elif" statement perform action when conditon is true 
   * "else" statement execute when condition of "if and elif" statement is false

In [ ]:
# Expression 
x = 45
print(x)

45


In [ ]:
# Multi-Line Statement
 
a,b,c,d = 4,5,6,7
print(a,b,c,d)

4 5 6 7


In [ ]:
# if -elif-else statement 

x =20 
if x==20 :
  print(f"x is {x}")
elif x == 30:
  print(f"x is {x}")
else:
  print(x)

x =30
if x==20 :
  print(f"x is {x}")
elif x == 30:
  print(f"x is {x}")
else:
  print(x)

x is 20
x is 30


x is 30


In [ ]:
city = "Jaipur"
if city == "New Delhi":
  print("Welcome to india capital")
elif city == "Mumbai":
  print("Welcome to economic capital if india")
else:
  print("pink city of india")


pink city of india


In [ ]:
num1 = 4
num2 = -2
if num2<0:
  if num1<0:
    print(num1+num2)
  else:
    print("num1 is positive number")
else:
  print("num2 is positive number")

num1 is positive number


# Loops And Control

Block of code is not use repeatly , so we use loops

Types of Loops
1. While - work on condition
2. For loop - work on iterable(string , list , tuple , set, etc.)


▶ Break - this statement break the loop

▶ Continue - this statement skip the current iteration

▶ Pass - this statement does nothing , only pass the iteration


⚛ List Comprehension - This method used to compress the syntax 

▶ Nested Loop 

    range() - built in function

    renge(start , stop , step size)
           |        \
           include   exclude 
        



In [ ]:
# For Loops in String

my_city = "Jaipur"
for i in my_city:
  print(i)


my_city = "Jaipur"
for i in my_city[ : : -1]:       # reverse print            [SI : EI : SS]
  print(i)

my_city = "Jaipur"
for i in my_city[ : : -2]:
  print(i)

my_city = "Jaipur"
for i in my_city[: : -3]:
  print(i)

In [ ]:
#  For Loops in List

my_list = [1,2,3,4,5,6,7,8,9]
for i in my_list:
  print(i)

my_list = [1,2,3,4,5,6,7,8,9]
for i in my_list:
  if i % 2 == 0:                # For even numbers
    print(i)

my_list = [1,2,3,4,5,6,7,8,9]
for i in my_list:
  if i % 2 == 1:                # For odd numbers
    print(i)


my_list = [1,2,3,4,5,6,7,8,9]
for i in my_list:
  if i % 2 != 0:                # For odd numbers
    print(i)


# list k element ka sqaure krke unko , list m hi print krvaya 
list_of_list = [1,2,3,4,5,6,7,8]
my_list=[]
for num in list_of_list:
  square = num **2                # " num **2 " or " num * num "
  my_list.append(square)          # append , last m add krta h 
print(my_list)


 
list_of_list = [1,2,3,4,5,6,7,8]
my_list = []
for num in list_of_list:
  if num % 2 == 0:
    square = num **2
    my_list.append(square)
print(my_list)


list_of_list = [1,2,3,4,5,6,7,8]
my_list = []
for num in list_of_list:
  if num % 2!= 0:
    square = num **2
    my_list.append(square)
print(my_list)


In [ ]:
# For Loops in tuple 
my_tuple = (1,2,3,4,5,6,7,8,9)
for i in my_list:
  print(i)
print(type(my_tuple))

In [ ]:
# For Loops in sets 
my_set = {1,2,3,4,5,6,7,8,9}
for i in my_list:
  print(i)
print(type(my_set))



In [ ]:
# While Loop

x = 0 
while x <10:
  print(x)
  x = x+1

# loop se bahar aakr 10 ko print kr dega , because 10 is not less then 10 , so condition are false 
print(x)

In [ ]:
# While loop in List

x = 0 
my_list = []
while x <10:
  my_list.append(x)
  x+=1
print(my_list)

In [ ]:
# Break Statement

x = 0 
while x < 10:
  x+=1
  if x == 3:
    break 
    print(x)
  else:
    print(x)

In [ ]:
# Continue Statement

x = 0 
while x < 10:
  x+=1
  if x == 3:
    continue 
    print(x)
  else:
    print(x)
    

In [ ]:
# Pass Statement 

x = 0 
while x < 10:
  x+=1
  if x == 3:
    pass 
    print(x)
  else:
    print(x)
    


In [ ]:
# this method use to compress the Syntax 

# Before without using List comprehension
list_of_list = [1,2,3,4,5]
my_list = []
for num in list_of_list :
  square = num **2
  my_list.append(square )
print(my_list)


# After using List Comprehension 
list_of_list = [1,2,3,4,5]
my_list = [num**2 for num in list_of_list]
print(my_list)


list_of_list = [1,2,3,4,5]
my_list = [num**3 for num in list_of_list]      # for cube 
print(my_list)


list_of_list = [1,2,3,4,5,6,7,8]
my_list = [num **2 for num in list_of_list if num%2 ==0]         # for even numbers square in list 
print(my_list)


list_of_list = [1,2,3,4,5,6,7,8]
my_list = [num **2 if num%2 ==0 else num **3 for num in list_of_list] # for print the even number "square" and left are print the  "cube"
print(my_list)

In [ ]:
# Nested loop 
for i in range(5):
  print(i)


list_of_list = []
for i in range(4):
  for j in range(3):
    list_of_list.append(i)     # i = 0           i =1        i =2       i = 3
print(list_of_list)            # j = 0 , 1 ,2    j = 0,1,2   j =0,1,2   j =0,1,2 
# append "i" , that reason output is [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3] , because child is complete life is live for one parent iteration 



list_of_list = []
for i in range(4):
  for j in range(3):
    list_of_list.append(j)         # i = 0           i =1        i =2       i = 3
print(list_of_list)                # j = 0 , 1 ,2    j = 0,1,2   j =0,1,2   j =0,1,2 
 
# append "j" , that reason output is [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2] , because child is complete life is live for one parent iteration



# with the help of List Comprehension
list_of_list = [i for i in range(4) for j in range(3)]
print(list_of_list)





In [ ]:
# Split method - this method split the words and give in the form of list 
my_intro = "my self jagat, AI and ML trainer"
my_words = my_intro.split(" ")
print(my_words)


# string k words ka first chaaracter output aaye list m 
my_intro = "my self jagat, AI and ML trainer"
my_words = my_intro.split(" ")
first_letter = []
second_letter = []
third_letter = []
for word in my_words:
  first_letter.append(word[0])
print(first_letter)

for word in my_words:
  second_letter.append(word[1])
print(second_letter)


for word in my_words:
  third_letter.append(word[2])           # string index out of range 
print(third_letter)



In [ ]:
# with the help of List Comprehension

my_intro = "my self daya AI and ML trainer"
my_words = my_intro.split(" ")

first_letter = [word[0] for word in my_words]
print(first_letter)




# with the help of set Comprehension 

my_intro = "my self daya AI and ML trainer"
my_words = my_intro.split(" ")

first_letter = {word[0] for word in my_words}
print(first_letter)


# with the help of Dict Comprehension

country_city_dict = {"India":"ND" , "USA":"NY"}
my_dict = {}
for country,city in country_city_dict.items():
  my_dict[city] = country
print(my_dict)


country_city = {"India" : "ND" , "USA" : "NY"}
my_dict = {city:country for country , city in country_city.items()}
print(my_dict)


# Function

1. User Defined Function

* Work according to user need 
* Statement of block of codes

          Syntax -  def functioname():
                       block of code 

       ↪ doc string represent work of your function

       ↪ doc string write in Triple pods 

2. Anonymous function 

            Syntax :-  lambda Input : expression 
                         |
                       keyword
            
            Example - a = lambda x : x**2
                      a(4)
                      output - 16 


3. Map Function - Mapping the two things , function and iterable 

        map(function , iterable)



4. Filter Function - It work only condition 

          my_list = [1,2,3,4,5,6,7]
          list(filter(lambda x : x>3 , my_list))
                                  |
                                  condition



 

In [ ]:
# user defined Function 

def greet():
   
  result = "Good Morning Daya"
  return result 
print(greet())


def add ():
   
  a = int(input("enter the num1 : "))
  b = int(input("enter the num2 : "))
  result = a+b
  return a+b
print(add())

Good Morning Daya
enter the num1 : 10
enter the num2 : 20
30


In [ ]:
# Positional Argument 

def calculation(a,b):

  print("Addition = " , a+b)
  print("Substraction = ",a-b)
  print("Multiplication = ",a*b)
  print("Division = " , a/b)
calculation(10,5)



addition 15
substraction 5
Multiplication 50
Division 100000


In [ ]:
# Concept of return

def add(a,b):
  result = a+b
  print(result)
  
add(10,5)


def add(a,b):
  result = a+b
  print(result)
print(add(10,5))   # none show , beacuse we are not "return any"


def add(a,b):
  result = a+b
  print(result)
  return result
print(add(10,5))    # return the result 

15
15
None
15
15


In [ ]:
# Default Argument 
def add(a , b=10):
  result = a + b
  return result 
add(5)       # "b" is by default take the value 10 


def add (a,b =10):
  result = a+b
  return result
add(5,15)           # in this b are not by default , because we take the value of b is 15


'''
def add(a,b = 10 , c):      # non-default argument follows default argument
  result = a+b+c
  print(result)
add(10,5)
'''

def add(a,b = 10 , c = 5):       # when we take default argument ,then after next argument will be default     
  result = a+b+c
  print(result)
add(10)

25


In [ ]:
# Keyword Argument

def interest(p,r,t):
  i = (p*r*t)/100
  return i
interest(5000 , 10 ,2)


def interest(p,r,t):
  i = (p*r*t)/100
  return i
interest(t=5000 , p=10 ,r=2)      #   this is a keyword argument , that are automatically find the value of argument sequence ,
                                  #   means follw the sequence of given argument 

1000.0

In [ ]:
# Extract first letter of sentence
def extract_first_letter(sentence):

  my_word = sentence.split(" ")
  first_letter = [word[0] for word in my_word]
  return first_letter

my_intro = "My self Daya Shanker Saini"
extract_first_letter(my_intro)


['M', 's', 'D', 'S', 'S']

In [ ]:
# Anonymous Function 
a = lambda  x : x**2      # lambda is a keyword 
print(a(4))

a = lambda  x : x**2
print(a(8))




a = lambda x,y : x+y
print(a(10,5))

16
64
15


In [ ]:
# Map Function
# map(function , iterable)
# 2 cheejo ki mapping krta h "function and iterable" ki 

my_list = [1,2,3,4,5,6,7,8]
list(map(lambda x :x**2 , my_list))




[1, 4, 9, 16, 25, 36, 49, 64]

In [ ]:
# Filter Function - kisi condition pr kaam krta h 
my_list = [1,2,3,4,5,6,7]
list(filter(lambda x : x>3 , my_list))   # yha pr condition diya " x>3 "



# condition k alawa agr or koi bhi action perform krate h tho input ko print kra dega yaaa fir input ko hi output m de dega 
my_list = [1,2,3,4,5,6,7]
list(filter(lambda x : x**2 , my_list))       # yha pr koi condition nhi h 



[4, 5, 6, 7]

In [ ]:
# Functools Function

# functools function ek saath reduce krta h given expression ko given iterable k saath 

import functools 
my_list = [1,2,3,4,5]
functools.reduce (lambda x,y : x+y , my_list)        




15

# Exception  Error 


In [ ]:
# Exception and error 

a = 10 
b = 0 
c = a/b              # show the - ZeroDivisionError: division by zero
print(c)

In [ ]:
try :
  a = 10
  b = 0
  c = a/b 
  print(c)
except ZeroDivisionError:          # isme error pta krke us error ko likh rhe h 
  print("Division by zero not allowed")



# try block m error aayega tb hi except block m jaayega , otherwise try block k code ko execute kr dega 
try :
  a = 10
  b = 5
  c = a/b 
  print(c)
except ZeroDivisionError:
  print("Division by zero not allowed")


Division by zero not allowed


In [ ]:
try :
  a = 10
  b = 0
  c = a/b 
  print(c)
except Exception as obj:          # it show the what error comes  , isme error ko pta kr rhe h 
  print(obj)




try :
  a = 10
  b = 0
  c = a/g
  print(c)
except Exception as obj:          
  print(obj)

division by zero
name 'g' is not defined


In [ ]:
try:
  a = 10 
  b = 5 
  c = a/b
  print(c)
except Exception as obj:
  print(obj)

else:
  print("Inside Else")
finally:
  print("Topic error and exception")

# isme Except block kaam nhi kr rha , because of in try block "not error found " and directly excute the else and finally block 



2.0
Inside Else
Topic error and exception


# Library

Instruction + variable = Function

collection of function = Modules

Collection of Modules = Packages 

Collection of Packages = Libraries 



⏩Numpy(Numerical Python) :-Library of python

Multi-Dimensional Array compare to list 
  1. Less memory
  2. Better Functionality
  3. Better Performance

In [ ]:
# One-Dimensional array 
import numpy as np
oned_array = np.array([1,2,3,4])      
print(oned_array)
oned_array




[1 2 3 4]


array([1, 2, 3, 4])

In [ ]:
# Two-dimensional array 
import numpy as np
twod_array = np.array([[1,2,3,4] , [5,6,7,8]])      
print(twod_array)
print(twod_array.shape)

twod_array

In [ ]:
# Three-Dimensional Array
import numpy as np
threed_array = np.array([[[1,2,3,4] ,[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(threed_array)
print(threed_array.shape)




In [ ]:


# N-Dimensional Array
import numpy as np
ndim_array = np.array([[[1,2,3,4],[5,6,7,8]] , [[9,10,11,12],[13,14,15,16]]])
print(ndim_array.ndim)

3


In [ ]:
# Size - represent number of item in array
import numpy as np
x = np.array([[[1,2,3,4],[5,6,7,8]] , [[9,10,11,12],[13,14,15,16]]])
print(x.size)

16


In [ ]:
# Dtype - Return the data type of array
import numpy as np
x = np.array([[[1,2,3,4],[5,6,7,8]] , [[9,10,11,12],[13,14,15,16]]])
print(x.dtype)

In [ ]:
# astype - change the type of data
import numpy as np
x = np.array([[[1,2,3,4],[5,6,7,8]] , [[9,10,11,12],[13,14,15,16]]])
y=x.astype("float64")
print(y)

In [ ]:
# check the size without array 
import numpy as np
import sys
s = [0,1,2,3,4,5,6,7,8,9]
print("one item memory", sys.getsizeof(s))
print("list of memory", sys.getsizeof(s)*len(s))

one item memory 136
list of memory 1360


In [ ]:
# check the sixze with array 
import numpy as np
import sys
s = [0,1,2,3,4,5,6,7,8,9]
x = np.array(s)          # "s" ko array bna diya 

print("size of item ", x.itemsize)
print("size of array" , x.size * x.itemsize)


# So array are less memory consume 

size of item  8
size of array 80


In [ ]:
# Check functionality -  Because why are use of array 

ls = [1,2,3]
try:
  list = ls + 4
  print(list)
except Exception as obj:
  print(obj)

try:
  x = np.array(ls)
  y = x+4
  print(y)
except Exception as obj:
  print(obj) 


# Functionality of array is better comparison to List , because we add an integer to array but not add integer in list 
# only list ko hi add kr skte h  list m 
# array k andr , list m integer add kr skte h , jbki list m add nhi kr skte  

can only concatenate list (not "int") to list
[5 6 7]


In [ ]:
# Array initialize with zeros
import numpy as np
zeros_array = np.zeros((3,3))     # by default data is float 
print(zeros_array)


import numpy as np
zeros_array = np.zeros((3,3) , dtype = int )    # data is in  int 
print(zeros_array)

In [ ]:
# Array  initialize with ones
import numpy as np
ones_array = np.ones((3,3))     # by default data is float 
print(ones_array)

import numpy as np
ones_array = np.ones((3,3) , dtype = int)     #  data is in integer 
print(ones_array)





In [ ]:
import numpy as np
ones_array = np.ones((8,9,10) , dtype = int)   
print(ones_array)

In [ ]:
# arange(Start , Stop , StepSize , dtype)

arange_array = np.arange(1,9,2 )
print(arange_array)

arange_array = np.arange(1,9,2,float )
print(arange_array)

arange_array = np.arange(1,9,2  ,None)
print(arange_array)


arange_array = np.arange(1,9,1 )      # stopping is not include
print(arange_array)


[1 3 5 7]
[1. 3. 5. 7.]
[1 3 5 7]
[1 2 3 4 5 6 7 8]


In [ ]:
# linspace(Start , Stop , num , endpoint , retstep)
# data are separable linearly 

my_array = np.linspace(10,20,10,endpoint = True , retstep = True)
print(my_array)





In [ ]:
my_array = np.linspace(10,20,10,endpoint = True , retstep = False)
print(my_array)

# retstep = 1.1111111111111112

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [ ]:
my_array = np.linspace(10,20,10,endpoint = False , retstep = True)
print(my_array)

# retstep = 1.0

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), 1.0)


In [ ]:
my_array = np.linspace(10,20,10,endpoint = False , retstep = False)
print(my_array)

In [ ]:

# Array With random number 

my_array = np.random.random((4,3)) # data type are always "float"
print(my_array)





In [ ]:
my_array = np.random.random((4,3)) # data type are always "float"
print(my_array)


In [ ]:
my_array = np.random.randint(0,6,(4,3)) 
print(my_array)

# 0 :- Start   ,  6 :- Stop   , (4,3) :- Shape

In [ ]:
my_array = np.full((4,3) , 49 )   # by default data type are "integer"
print(my_array)



my_array = np.full((4,3) , 49  , dtype = float)    
print(my_array)

In [ ]:
# Indexing Of Array 

# Three-D Array

x = np.array([[[1,2,3,4] ,[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(x[1,1,1])    # this is 3-dimensional array , so we can give 3 argument . like as x[1,1,1] 

                    # agr 2-dimensional array hota tho  2 argument dene pdte , one hota tho one argument dena pdta




y = np.array([[[1,2,3] , [4,5,6]],
              [[7,8,9] , [10,11,12]],
              [[13,14,15] , [16,17,18]]])
print(y[1,1,1])



In [ ]:
y = np.array([[[1,2,3] , [4,5,6]],
              [[7,8,9] , [10,11,12]],
              [[13,14,15] , [16,17,18]]])
print(y[0:2 , 0:1 , 0:2])

In [ ]:
# Transpose - how to transpose array in machine learning 

my_array = np.random.randint(0,8,(3,4))
print(my_array)
print(my_array.shape)

x = np.transpose(my_array)
print(x)
print(x.shape)

In [ ]:
my_array = np.random.randint(0,8,(3,4))
print(my_array)


x = np.transpose(my_array)
print(x)

# it transpose the "row" into "column"  && "column" into "row" .
 

In [ ]:
array = np.random.randint(0,8,(8,3))
print(array)

reshape_array = np.reshape(array,(2,3,4))
print(reshape_array)

# multiple of "array" and "reshape_array" are same , because number of "items" are not change

In [ ]:
array = np.random.randint(0,8,(8,2))          # yha pr multiple (8,2) ka 16 h 
print(array)

reshape_array = np.reshape(array,(2,3,4))     # yha pr multiple (2,3,4) ka 24 h 
print(reshape_array)
# jbki dono ka multiple same hona chaiye , kyoki number of items change nhi hote 
# Error: cannot reshape array of size 16 into shape (2,3,4)

In [ ]:
# Re-Size the array

array = np.random.randint(0,8,(8,3))
print(array)

resize_array = np.resize(array,(2,4,4))   # number of element is change 
print(resize_array)

[[4 1 3]
 [5 7 3]
 [2 5 2]
 [5 1 0]
 [4 2 4]
 [5 2 6]
 [0 6 7]
 [3 2 4]]
[[[4 1 3 5]
  [7 3 2 5]
  [2 5 1 0]
  [4 2 4 5]]

 [[2 6 0 6]
  [7 3 2 4]
  [4 1 3 5]
  [7 3 2 5]]]


In [ ]:
# Complete(2,3,4,5,6,7,8,9,10......) array ko One-D m convert krna ho tho

array = np.random.randint(0,8,(8,3))
print(array)

resize_array = np.resize(array,(2,4,4))  
print(resize_array.flatten())

# number of item cannot be changed

[[0 1 4]
 [5 7 6]
 [6 7 4]
 [6 0 6]
 [5 7 6]
 [5 0 3]
 [0 7 0]
 [7 2 0]]
[0 1 4 5 7 6 6 7 4 6 0 6 5 7 6 5 0 3 0 7 0 7 2 0 0 1 4 5 7 6 6 7]
